### ISSUE TITLE
It doesn't build 😅

### ISSUE THREAD

**Issue by AdrianKoshka** [shymega/singlerss#1]
```
# github.com/shymega/singlerss/internal/config
internal/config/config.go:5:2: imported and not used: "github.com/inconshreveable/log15" as log
make: *** [Makefile:12: build] Error 2
```

**Comment by shymega** [comment]
Sorry to hear about your problem building singlerss.

This is a problem with my last commit to include a logger library, which I haven't yet utilised in `the internal/config` package. 

Currently working on a patch.
